---
- hosts: all
  become: yes

  tasks:
    - name: Copy setup_zsh.sh to the target
      copy:
        src: scripts/setup_zsh/setup_zsh.sh
        dest: /home/yalt/setup_zsh.sh
        owner: yalt
        group: yalt
        mode: '0755'

    - name: Run the script as user yalt using sudo
      command: sudo -u yalt /home/yalt/setup_zsh.sh
      register: script_output
      ignore_errors: yes

    - name: Display script output
      debug:
        var: script_output.stdout_lines